# =============================================================================
# Data Loaders — resource file loaders for tariff programs
# =============================================================================
# Loads USMCA shares, MFN exemption shares, metal content, 232 derivatives,
# 232 annex products, fentanyl carveouts, and floor exemptions.
#
# Split from helpers.R. Sourced by helpers.R for backward compatibility.
# Direct consumers can source this file alone (requires policy_params.R).

library(tidyverse)
library(here)

load_232_derivative_products <- function(path = here('resources', 's232_derivative_products.csv'),
                                         effective_date = NULL) {
  if (!file.exists(path)) {
    message('  232 derivative products file not found: ', path)
    return(NULL)
  }

  products <- read_csv(path, col_types = cols(
    hts_prefix = col_character(),
    ch99_code = col_character(),
    derivative_type = col_character(),
    effective_date = col_date(format = '')
  ))

  # Filter by effective_date if provided
  if (!is.null(effective_date) && 'effective_date' %in% names(products)) {
    n_before <- nrow(products)
    products <- products %>%
      filter(is.na(effective_date) | effective_date <= !!effective_date)
    n_filtered <- n_before - nrow(products)
    if (n_filtered > 0) {
      message('  Filtered out ', n_filtered, ' derivative entries not yet effective at ', effective_date)
    }
  }

  message('  Loaded ', nrow(products), ' Section 232 derivative product prefixes')
  return(products)
}


#' Load the Taiwan civil-aircraft Section 232 exemption product list
#'
#' Products exempt from the Section 232 metals annex under U.S. note 35(c) /
#' heading 9903.96.03 (Taiwan civil-aircraft components), effective 2026 rev_9.
#' Extracted from the rev_9 Chapter 99 PDF (note 35(c) subdivision list).
#'
#' @param path Path to s232_aircraft_exempt_taiwan.csv
#' @return Character vector of HTS8 codes (empty if file missing)
load_232_aircraft_exempt_taiwan <- function(
  path = here('resources', 's232_aircraft_exempt_taiwan.csv')
) {
  if (!file.exists(path)) {
    warning('Taiwan aircraft 232 exemption file not found: ', path)
    return(character(0))
  }
  df <- read_csv(path, col_types = cols(.default = col_character()))
  unique(df$hts8)
}


#' Load floor country product exemptions
#'
#' Products exempt from the 15% tariff floor for EU, Japan, S. Korea,
#' Switzerland/Liechtenstein. Categories: PTAAP (agricultural/natural
#' resources), civil aircraft, non-patented pharmaceuticals. Parsed from
#' US Notes to Chapter 99 by scrape_us_notes.R --floor-exemptions.
#'
#' @param path Path to floor_exempt_products.csv
#' @return Tibble with hts8, category, country_group, ch99_code; or empty tibble if missing
load_floor_exempt_products <- function(path = here('resources', 'floor_exempt_products.csv')) {
  if (!file.exists(path)) {
    message('  Floor exempt products file not found: ', path)
    return(tibble(hts8 = character(), category = character(),
                  country_group = character(), ch99_code = character()))
  }

  products <- read_csv(path, col_types = cols(.default = col_character()))
  message('  Loaded ', nrow(products), ' floor exempt products (',
          n_distinct(products$hts8), ' unique HTS8)')
  return(products)
}


#' Load revision-specific floor country product exemptions
#'
#' Tries per-revision file first (data/us_notes/floor_exempt_{revision}.csv),
#' then falls back to the static resources/floor_exempt_products.csv.
#'
#' @param revision_id Character revision ID (e.g., 'rev_18', '2026_basic')
#' @return Tibble with hts8, category, country_group, ch99_code; or empty tibble
load_revision_floor_exemptions <- function(revision_id) {
  # Try per-revision file first
  revision_path <- here('data', 'us_notes', paste0('floor_exempt_', revision_id, '.csv'))
  if (file.exists(revision_path)) {
    products <- read_csv(revision_path, col_types = cols(.default = col_character()))
    message('  Loaded ', nrow(products), ' floor exempt products for ', revision_id,
            ' (', n_distinct(products$hts8), ' unique HTS8)')
    return(products)
  }

  # Fall back to static file
  message('  No per-revision floor exemptions for ', revision_id,
          '; using static fallback')
  return(load_floor_exempt_products())
}


#' Load product-level USMCA utilization shares from USITC DataWeb SPI data
#'
#' Per-HTS10 x country USMCA shares from DataWeb SPI programs S/S+.
#' Generated by src/download_usmca_dataweb.R.
#' Returns NULL if file not found (triggers fallback to binary eligibility).
#'
#' Modes (from policy_params$USMCA_SHARES$mode):
#'   'h2_average' (default): averages months 7-12 of the configured year. Reflects post-tariff
#'      steady-state USMCA utilization (CA ~85-88%, MX ~85-88%) without monthly noise.
#'   'annual': loads resources/usmca_product_shares_{year}.csv
#'   'monthly': loads resources/usmca_product_shares_{year}_{MM}.csv based on effective_date
#'   'fixed_month': loads resources/usmca_product_shares_{year}_{MM}.csv using configured month
#'   'hybrid_rolling': Q1 average for Jan-Mar, 3-month rolling average (m, m-1, m-2) from April.
#'      Smooths the mid-2025 USMCA utilization jump while capturing the behavioral shift.
#'      Rolling uses available months only; falls back to annual if no monthly files found.
#'
#' @param policy_params Policy params list (uses usmca_shares mode/year)
#' @param path Override path (ignores mode/year selection if provided)

load_usmca_product_shares <- function(policy_params = NULL, path = NULL, effective_date = NULL) {
  if (is.null(path)) {
    mode <- policy_params$USMCA_SHARES$mode %||% 'annual'
    year <- policy_params$USMCA_SHARES$year %||% NULL

    if (mode == 'none') {
      # Scenario: assume 0% USMCA utilization for every CA/MX product-country pair.
      # Return an empty tibble with the correct schema. The caller in
      # src/06_calculate_rates.R reads `pp$USMCA_SHARES$mode` directly and
      # short-circuits the USMCA application block entirely when mode == 'none',
      # so this tibble is never joined against real rates.
      message('  USMCA mode = none: treating all CA/MX pairs as 0% utilization')
      return(tibble(
        hts10 = character(0),
        cty_code = character(0),
        usmca_share = numeric(0)
      ))
    }

    if (mode == 'h2_average') {
      # Average months 7-12: post-tariff steady-state USMCA utilization
      year <- year %||% 2025L
      monthly_shares <- list()
      for (m in 7L:12L) {
        m_path <- here('resources', sprintf('usmca_product_shares_%d_%02d.csv', year, m))
        if (file.exists(m_path)) {
          monthly_shares[[length(monthly_shares) + 1L]] <- read_csv(
            m_path, col_types = cols(.default = col_guess(),
                                     hts10 = col_character(), cty_code = col_character(),
                                     usmca_share = col_double()), show_col_types = FALSE
          )
        }
      }
      if (length(monthly_shares) > 0) {
        combined <- bind_rows(monthly_shares)
        has_values <- all(c('total_value', 'usmca_value') %in% names(combined))
        if (has_values) {
          # Value-weighted aggregation: sum(usmca_value) / sum(total_value)
          combined <- combined %>%
            group_by(hts10, cty_code) %>%
            summarise(
              usmca_share = if_else(sum(total_value, na.rm = TRUE) > 0,
                                    sum(usmca_value, na.rm = TRUE) / sum(total_value, na.rm = TRUE),
                                    0),
              .groups = 'drop'
            )
          message('  Loaded USMCA H2 average (value-weighted): ', nrow(combined),
                  ' product-country pairs (', length(monthly_shares), ' months, Jul-Dec ', year, ')')
        } else {
          # Fallback: simple average of ratios (legacy monthly CSVs without value columns)
          combined <- combined %>%
            group_by(hts10, cty_code) %>%
            summarise(usmca_share = mean(usmca_share, na.rm = TRUE), .groups = 'drop')
          message('  Loaded USMCA H2 average (ratio-averaged, no value cols): ', nrow(combined),
                  ' product-country pairs (', length(monthly_shares), ' months, Jul-Dec ', year, ')')
        }
        return(combined)
      } else {
        message('  No H2 monthly USMCA files found for ', year, ' — falling back to annual')
        path <- here('resources', paste0('usmca_product_shares_', year, '.csv'))
      }

    } else if (mode == 'fixed_month') {
      fixed_month <- policy_params$USMCA_SHARES$month %||% 12L
      year <- year %||% 2025L
      monthly_path <- here('resources', sprintf('usmca_product_shares_%d_%02d.csv', year, as.integer(fixed_month)))
      if (file.exists(monthly_path)) {
        path <- monthly_path
      } else {
        message('  Fixed-month USMCA file not found for ', year, '-', sprintf('%02d', fixed_month),
                ' — falling back to annual')
        path <- here('resources', paste0('usmca_product_shares_', year, '.csv'))
      }
    } else if (mode == 'hybrid_rolling' && !is.null(effective_date)) {
      # Q1 average for Jan-Mar; 3-month rolling (m, m-1, m-2) from April onward
      eff <- as.Date(effective_date)
      year <- year %||% as.integer(format(eff, '%Y'))
      month_num <- as.integer(format(eff, '%m'))
      if (eff < as.Date(paste0(year, '-01-01'))) month_num <- 1L
      if (eff > as.Date(paste0(year, '-12-31'))) month_num <- 12L

      if (month_num <= 3L) {
        # Q1: average all available months 1-3
        window <- 1L:3L
      } else {
        # Rolling: months m, m-1, m-2
        window <- (month_num - 2L):month_num
      }

      # Load available monthly files in the window
      monthly_shares <- list()
      for (m in window) {
        m_path <- here('resources', sprintf('usmca_product_shares_%d_%02d.csv', year, m))
        if (file.exists(m_path)) {
          monthly_shares[[length(monthly_shares) + 1L]] <- read_csv(
            m_path, col_types = cols(hts10 = col_character(), cty_code = col_character(),
                                     usmca_share = col_double()), show_col_types = FALSE
          )
        }
      }

      if (length(monthly_shares) > 0) {
        combined <- bind_rows(monthly_shares)
        has_values <- all(c('total_value', 'usmca_value') %in% names(combined))
        window_label <- paste0(sprintf('%02d', window[1]), '-', sprintf('%02d', window[length(window)]))
        if (has_values) {
          combined <- combined %>%
            group_by(hts10, cty_code) %>%
            summarise(
              usmca_share = if_else(sum(total_value, na.rm = TRUE) > 0,
                                    sum(usmca_value, na.rm = TRUE) / sum(total_value, na.rm = TRUE),
                                    0),
              .groups = 'drop'
            )
          message('  Loaded USMCA hybrid rolling (value-weighted): ', nrow(combined),
                  ' product-country pairs (', length(monthly_shares), ' months in window ',
                  window_label, ')')
        } else {
          combined <- combined %>%
            group_by(hts10, cty_code) %>%
            summarise(usmca_share = mean(usmca_share, na.rm = TRUE), .groups = 'drop')
          message('  Loaded USMCA hybrid rolling (ratio-averaged): ', nrow(combined),
                  ' product-country pairs (', length(monthly_shares), ' months in window ',
                  window_label, ')')
        }
        return(combined)
      } else {
        message('  No monthly USMCA files found for hybrid rolling — falling back to annual')
        path <- here('resources', paste0('usmca_product_shares_', year, '.csv'))
      }

    } else if (mode == 'monthly' && !is.null(effective_date)) {
      eff <- as.Date(effective_date)
      target_year  <- as.integer(format(eff, '%Y'))
      target_month <- as.integer(format(eff, '%m'))

      # Walk backward to collect available monthly files. The first file found
      # is the primary share source for trade-active pairs; subsequent files
      # are fallback for pairs missing from the primary (typical for early-
      # year YTD queries where DataWeb's universe is narrower than the prior
      # year's any-month universe — ~9k tail HTS10s drop out of 2026_01 vs
      # 2025_12 for example, ~$3.5B of 2024 import value at ~90% historical
      # USMCA share). Cap at 6 monthly files of fallback to avoid using
      # very stale shares; cap walkback at 120 steps (10 years) to find the
      # primary even if there's a publication gap.
      files_to_load <- character(0)
      primary_y <- NA_integer_; primary_m <- NA_integer_
      y <- target_year; m <- target_month
      for (step in seq_len(120L)) {
        candidate <- here('resources', sprintf('usmca_product_shares_%d_%02d.csv', y, m))
        if (file.exists(candidate)) {
          files_to_load <- c(files_to_load, candidate)
          if (length(files_to_load) == 1L) {
            primary_y <- y; primary_m <- m
          }
          if (length(files_to_load) >= 6L) break
        }
        m <- m - 1L
        if (m < 1L) { m <- 12L; y <- y - 1L }
      }

      if (length(files_to_load) > 0L) {
        if (primary_y != target_year || primary_m != target_month) {
          message(sprintf('  Monthly USMCA file not found for %d-%02d — using most recent available: %d-%02d',
                          target_year, target_month, primary_y, primary_m))
        }
        primary <- read_csv(files_to_load[1L], col_types = cols(
          hts10 = col_character(), cty_code = col_character(),
          usmca_share = col_double(), .default = col_guess()
        ), show_col_types = FALSE)
        if (length(files_to_load) > 1L) {
          augmented <- primary
          for (extra in files_to_load[-1L]) {
            prior <- read_csv(extra, col_types = cols(
              hts10 = col_character(), cty_code = col_character(),
              usmca_share = col_double(), .default = col_guess()
            ), show_col_types = FALSE)
            new_rows <- prior %>% anti_join(augmented, by = c('hts10', 'cty_code'))
            if (nrow(new_rows) > 0L) augmented <- bind_rows(augmented, new_rows)
          }
          n_fill <- nrow(augmented) - nrow(primary)
          if (n_fill > 0L) {
            message(sprintf('  USMCA monthly: augmented primary %s with %d fallback rows from %d prior month(s)',
                            basename(files_to_load[1L]), n_fill, length(files_to_load) - 1L))
          }
          message('  Loaded USMCA product shares (with fallback): ', nrow(augmented),
                  ' product-country pairs')
          return(augmented)
        }
        message('  Loaded USMCA product shares: ', nrow(primary),
                ' product-country pairs from ', basename(files_to_load[1L]))
        return(primary)
      } else {
        message('  No monthly USMCA files found — falling back to annual')
        path <- here('resources', paste0('usmca_product_shares_',
                                          year %||% target_year, '.csv'))
      }
    } else {
      if (!is.null(year)) {
        path <- here('resources', paste0('usmca_product_shares_', year, '.csv'))
      } else {
        path <- here('resources', 'usmca_product_shares.csv')
      }
    }
  }
  if (!file.exists(path)) {
    message('  USMCA product shares file not found — using binary eligibility')
    return(NULL)
  }
  shares <- read_csv(path, col_types = cols(
    hts10 = col_character(),
    cty_code = col_character(),
    usmca_share = col_double()
  ))
  message('  Loaded USMCA product shares: ', nrow(shares),
          ' product-country pairs from ', basename(path))
  return(shares)
}


#' Load MFN exemption shares (FTA/GSP preference utilization)
#'
#' HS2 x country exemption shares computed from Census calculated duty data.
#' effective_mfn = mfn_rate * (1 - exemption_share).
#' Sourced from Tariff-ETRs project. Returns NULL if file not found.
#'
#' @param path Path to mfn_exemption_shares.csv

load_mfn_exemption_shares <- function(path = here('resources', 'mfn_exemption_shares.csv')) {
  if (!file.exists(path)) {
    message('  MFN exemption shares file not found — using statutory base rates')
    return(NULL)
  }
  shares <- read_csv(path, col_types = cols(
    hs2 = col_character(),
    cty_code = col_character(),
    exemption_share = col_double()
  ))
  # Clamp exemption shares to [0, 1]
  shares <- shares %>%
    mutate(exemption_share = pmin(pmax(exemption_share, 0), 1))
  message('  Loaded MFN exemption shares: ', nrow(shares), ' HS2-country pairs')
  return(shares)
}


#' Load fentanyl carve-out product lists
#'
#' Product-specific fentanyl rate carve-outs: energy/critical minerals (CA) and
#' potash (CA/MX) receive a lower fentanyl rate than the general blanket.
#' Product lists sourced from Tariff-ETRs config (US Note 2 subdivisions).
#'
#' @param path Path to fentanyl_carveout_products.csv

load_fentanyl_carveouts <- function(path = here('resources', 'fentanyl_carveout_products.csv')) {
  if (!file.exists(path)) {
    message('  Fentanyl carve-out products file not found: ', path)
    return(NULL)
  }

  carveouts <- read_csv(path, col_types = cols(
    hts8 = col_character(),
    ch99_code = col_character(),
    category = col_character()
  ))

  message('  Loaded ', nrow(carveouts), ' fentanyl carve-out product prefixes (',
          n_distinct(carveouts$category), ' categories)')
  return(carveouts)
}


#' Load metal content shares for Section 232 derivative products
#'
#' For derivative 232 products, the tariff applies only to the metal content
#' portion of customs value. This function returns per-product metal shares.
#'
#' Three methods:
#'   flat: All derivative products get metal_share = flat_share (default 0.50)
#'   cbo:  Product-level buckets from resources/cbo/ files
#' Load Section 232 annex product classification
#'
#' Reads the annex product mapping from the static resource file. Returns a
#' tibble with hts_prefix and s232_annex columns for prefix-matching in
#' 06_calculate_rates.R. When the resource file is empty (header only), returns
#' an empty tibble — the annex rate override step becomes a no-op.
#'
#' @param effective_date Date to filter entries by effective_date column
#' @param resource_path Path to s232_annex_products.csv

load_annex_products <- function(effective_date = NULL,
                                resource_path = here('resources', 's232_annex_products.csv')) {
  if (!file.exists(resource_path)) {
    return(tibble(hts_prefix = character(), s232_annex = character()))
  }

  annex_map <- read_csv(resource_path, col_types = cols(.default = col_character()))

  if (nrow(annex_map) == 0) {
    message('  Annex products: resource file empty (pending HTS JSON)')
    return(tibble(hts_prefix = character(), s232_annex = character()))
  }

  # Filter by effective_date if column is present
  if ('effective_date' %in% names(annex_map) && !is.null(effective_date)) {
    annex_map <- annex_map %>%
      filter(is.na(effective_date) | effective_date <= as.character(!!effective_date))
  }

  annex_map %>%
    select(hts_prefix, s232_annex = annex) %>%
    mutate(s232_annex = paste0('annex_', s232_annex)) %>%
    distinct(hts_prefix, .keep_all = TRUE)
}


#'         (high=0.75, low=0.25, copper=0.90)
#'   bea:  HS10-level shares from BEA 2017 Detail I-O table
#'         (resources/metal_content_shares_bea_hs10.csv)
#'
#' Products in primary_chapters (72, 73, 76) always get metal_share = 1.0.
#' Non-derivative products outside primary chapters get metal_share = 1.0
#' (no metal adjustment — they don't have 232 rates).
#'
#' @param metal_cfg Metal content config list from policy_params.yaml
#' @param hts10_codes Character vector of HTS10 codes to compute shares for
#' @param derivative_hts10 Character vector of HTS10 codes identified as 232
#'   derivatives. Only these products receive metal_share < 1.0.
#' @return Tibble with hts10 and metal_share columns
load_metal_content <- function(metal_cfg = NULL, hts10_codes = character(0),
                               derivative_hts10 = character(0)) {
  if (length(hts10_codes) == 0) {
    return(tibble(hts10 = character(), metal_share = numeric(),

                  steel_share = numeric(), aluminum_share = numeric(),
                  copper_share = numeric(), other_metal_share = numeric()))
  }

  method <- if (!is.null(metal_cfg)) metal_cfg$method %||% 'flat' else 'flat'
  flat_share <- if (!is.null(metal_cfg)) metal_cfg$flat_share %||% 0.50 else 0.50
  primary_chapters <- if (!is.null(metal_cfg)) unlist(metal_cfg$primary_chapters) else c('72', '73', '76')

  # Start with all products at metal_share = 1.0 (full metal / no adjustment)
  # and zero-filled per-type columns. The zero-filled schema keeps bind_rows()
  # stable across revisions; downstream logic decides whether these per-type
  # shares are informative enough to use.
  result <- tibble(
    hts10 = hts10_codes,
    metal_share = 1.0,
    steel_share = 0,
    aluminum_share = 0,
    copper_share = 0,
    other_metal_share = 0
  )

  # Flag derivative products — only these get metal_share < 1.0
  is_derivative <- result$hts10 %in% derivative_hts10

  if (sum(is_derivative) == 0) {
    message('  Metal content: no derivative products to adjust')
    return(result)
  }

  if (method == 'flat') {
    result$metal_share[is_derivative] <- flat_share
    message('  Metal content: flat method (', round(flat_share * 100),
            '% for ', sum(is_derivative), ' derivatives)')

  } else if (method == 'cbo') {
    cbo_high_share <- if (!is.null(metal_cfg)) metal_cfg$cbo_high_share %||% 0.75 else 0.75
    cbo_low_share <- if (!is.null(metal_cfg)) metal_cfg$cbo_low_share %||% 0.25 else 0.25
    cbo_copper_share <- if (!is.null(metal_cfg)) metal_cfg$cbo_copper_share %||% 0.90 else 0.90

    # Load CBO bucket files
    cbo_dir <- here('resources', 'cbo')
    high_path <- file.path(cbo_dir, 'alst_deriv_h.csv')
    low_path <- file.path(cbo_dir, 'alst_deriv_l.csv')
    copper_path <- file.path(cbo_dir, 'copper.csv')

    cbo_shares <- tibble(hts10 = character(), metal_share = numeric())

    if (file.exists(copper_path)) {
      copper <- read_csv(copper_path, col_types = cols(I_COMMODITY = col_character()))
      cbo_shares <- bind_rows(cbo_shares,
        tibble(hts10 = copper$I_COMMODITY, metal_share = cbo_copper_share))
    }
    if (file.exists(high_path)) {
      high <- read_csv(high_path, col_types = cols(I_COMMODITY = col_character()))
      cbo_shares <- bind_rows(cbo_shares,
        tibble(hts10 = high$I_COMMODITY, metal_share = cbo_high_share))
    }
    if (file.exists(low_path)) {
      low <- read_csv(low_path, col_types = cols(I_COMMODITY = col_character()))
      cbo_shares <- bind_rows(cbo_shares,
        tibble(hts10 = low$I_COMMODITY, metal_share = cbo_low_share))
    }

    # Priority: copper > high > low (first match kept)
    cbo_shares <- cbo_shares %>%
      distinct(hts10, .keep_all = TRUE)

    # Only apply CBO shares to derivative products
    result <- result %>%
      left_join(cbo_shares %>% rename(cbo_share = metal_share), by = 'hts10') %>%
      mutate(
        metal_share = case_when(
          !is_derivative ~ 1.0,               # non-derivatives stay at 1.0
          !is.na(cbo_share) ~ cbo_share,      # CBO match for derivatives
          TRUE ~ flat_share                    # fallback to flat for unmatched derivatives
        )
      ) %>%
      select(-cbo_share)

    n_cbo <- sum(!is.na(cbo_shares$hts10[cbo_shares$hts10 %in% derivative_hts10]))
    message('  Metal content: CBO method (', n_cbo, ' of ', sum(is_derivative),
            ' derivatives matched; high=', cbo_high_share, ', low=', cbo_low_share,
            ', copper=', cbo_copper_share, ')')

  } else if (method == 'bea') {
    # BEA I-O table shares at HS10 level (per-metal-type detail).
    # File generated by Tariff-ETRs build_metal_content_shares.R from 2017 BEA
    # Detail Use Table and HS10->NAICS->BEA crosswalk chain.
    bea_path <- here('resources', 'metal_content_shares_bea_hs10.csv')
    if (!file.exists(bea_path)) {
      stop('BEA metal content file not found: ', bea_path,
           '\nCopy from Tariff-ETRs or switch to flat/cbo method.')
    }

    bea_shares <- read_csv(bea_path, col_types = cols(
      hs10 = col_character(),
      .default = col_double()
    )) %>%
      select(hts10 = hs10,
             bea_steel = steel_share, bea_aluminum = aluminum_share,
             bea_copper = copper_share, bea_other = other_metal_share,
             bea_metal = metal_share)

    # metal_share gated on is_derivative (only derivatives get < 1.0).
    # Per-type shares populated for ALL BEA-matched products: copper heading
    # scaling needs copper_share on non-derivative ch74 products; stacking
    # guards on rate_232 > 0 so non-232 products are unaffected.
    result <- result %>%
      left_join(bea_shares, by = 'hts10') %>%
      mutate(
        metal_share = case_when(
          !is_derivative ~ 1.0,              # non-derivatives stay at 1.0
          !is.na(bea_metal) ~ bea_metal,     # BEA match for derivatives
          TRUE ~ flat_share                   # fallback to flat for unmatched derivatives
        ),
        steel_share       = pmin(if_else(!is.na(bea_steel), bea_steel, 0), 1.0),
        aluminum_share    = pmin(if_else(!is.na(bea_aluminum), bea_aluminum, 0), 1.0),
        copper_share      = pmin(if_else(!is.na(bea_copper), bea_copper, 0), 1.0),
        other_metal_share = pmin(if_else(!is.na(bea_other), bea_other, 0), 1.0)
      ) %>%
      select(-starts_with('bea_'))

    n_bea <- sum(bea_shares$hts10 %in% derivative_hts10)
    message('  Metal content: BEA method (', n_bea, ' of ', sum(is_derivative),
            ' derivatives matched; fallback=', flat_share, ')')

  } else {
    warning('Unknown metal_content method: ', method, '. Using flat fallback.')
    result$metal_share[is_derivative] <- flat_share
  }

  # Force primary chapters (72, 73, 76) to metal_share = 1.0 regardless of
  # derivative flag. These are base metal products — the tariff applies to
  # their full customs value, not a metal content fraction.
  #
  is_primary <- substr(result$hts10, 1, 2) %in% primary_chapters
  if (any(is_primary)) {
    result$metal_share[is_primary] <- 1.0
    result$steel_share[is_primary] <- 0
    result$aluminum_share[is_primary] <- 0
    result$copper_share[is_primary] <- 0
    result$other_metal_share[is_primary] <- 0
  }

  return(result)
}
